### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by tirilo555** [ushainformatique/whatacart#12]
Error during installation
http://prntscr.com/hbvzqk
I tried with different versions php and mysql but always it was with the same error

**Comment by ushainformatique** [comment]
I can see the exact error but it is related to Swift transport. Could you please tell the exact error?

**Comment by tirilo555** [comment]
Currently i installed application. But it was possible if installing with demo data. Error appear during installation without demo data.

**Comment by ushainformatique** [comment]
Ok I would try and let you know.

**Comment by ushainformatique** [comment]
Yup you are right. Please replace this file and your issue would be resolved. We would be including it in next release as a fix.
[AuthDataManager.zip](https://github.com/ushainformatique/whatacart/files/1543004/AuthDataManager.zip)

**Comment by mlaxwong** [comment]
After replace file I able to reach 80%, but error again.

![error1](https://user-images.githubusercontent.com/11769661/34524266-d2073d70-f0d5-11e7-99eb-a46e11168d2e.png)
![error2](https://user-images.githubusercontent.com/11769661/34524267-d246d48a-f0d5-11e7-9ce7-2d9aacf2c24f.png)

**Comment by ushainformatique** [comment]
Could you please set debug to true in instance.install.php and let me know the exact error which you are getting?

**Comment by ushainformatique** [comment]
Closing this issue.
