### ISSUE TITLE
Change language!

### ISSUE THREAD

**Issue by anhnam00** [ushainformatique/whatacart#13]
Hello all, 
I'm having problem with change language,  i ran yii message ./message/config.php to gen vi-VN language. it worked. i translated and created vi-VN at Manage Languages . But when i changed to vi-VN lanuage, my shop isn't translated. i tried adding i18n into @common/config/main.php but still not worked. 

Please help me!
Thanks and sorry for my English.

**Comment by ushainformatique** [comment]
Please write your steps after running the message command so that i can understand.

**Comment by anhnam00** [comment]
Thanks for your reply!

My Steps after running the mesage command: 

1. Add i18n into Fontend config.
![1](https://user-images.githubusercontent.com/3665978/33363795-6d8ea7fc-d514-11e7-9aad-64d3085c12e9.PNG)

2. Create vi-VN language on Localization.
![2](https://user-images.githubusercontent.com/3665978/33364024-377f19e8-d515-11e7-918c-647805a043f4.PNG)

3. Change language on frontend.
![3](https://user-images.githubusercontent.com/3665978/33364125-9feac91e-d515-11e7-96bf-51ece087c3c1.PNG)

After changed Vietnam language but language still English language default.

Please help me!

**Comment by ushainformatique** [comment]
We would reply back to you shortly.

**Comment by anhnam00** [comment]
Hope to get your answer soon

**Comment by ushainformatique** [comment]
There is no issue as such. You have your data in english but not in the new language. You can purchase this extension http://whatacart.com/extension/4 and once you execute it the data would be there in your language and than you can edit from admin.

**Comment by ushainformatique** [comment]
I am closing this issue. You can purchase the extension as i mentioned.
