### ISSUE TITLE
During Install with composer no folder vendor/ushainformatique created

### ISSUE THREAD

**Issue by ppblaauw** [ushainformatique/whatacart#14]
When Installing whatacart using 
composer create-project ushainformatique/whatacart .
in public_html folder

When going to the site the following error is shown:
PHP Warning:  require(./vendor/ushainformatique/yiichimp/library/config/bootstrap.php): failed to open stream: No such file or directory in 

After copying the /vendor/ushainformatique directory from a downloaded zip file can go further with installing.

**Comment by ushainformatique** [comment]
Its strange we have tested it many times and it works completely fine. We would test and let you know.

**Comment by ushainformatique** [comment]
It is working fine so closing it.
