### ISSUE TITLE
An internal server error occurred

### ISSUE THREAD

**Issue by ppblaauw** [ushainformatique/whatacart#15]
Fresh install of whatacart

going to: 
backend/index.php/catalog/products/default/index
backend/index.php/home/default/dashboard
backend/index.php/catalog/products/review/index

Error Message:
An internal server error occurred.

The above error occurred while the Web server was processing your request.
Please contact us if you think this is a server error. Thank you.

**Comment by ppblaauw** [comment]
In debug mode
using MySql Database

backend/index.php/catalog/products/default/index  
  
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #37 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'yii2shopd.tpt.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
The SQL being executed was: SELECT COUNT(*) FROM (SELECT `tp`.*, `tpt`.`name` FROM `tbl_product_category` `tpc`, `tbl_product_category_mapping` `tpcm`, `tbl_product` `tp`, `tbl_product_translated` `tpt` WHERE tpcm.data_category_id = '1' AND tpcm.category_id = tpc.id AND tpcm.product_id = tp.id AND tp.id = tpt.owner_id AND tpt.language = 'en-US' GROUP BY `tp`.`id`) `c`

backend/index.php/home/default/dashboard

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #37 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'yii2shopd.tpt.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
The SQL being executed was: SELECT `tp`.*, `tpt`.`name` FROM `tbl_product_category` `tpc`, `tbl_product_category_mapping` `tpcm`, `tbl_product` `tp`, `tbl_product_translated` `tpt` WHERE tpcm.data_category_id = '1' AND tpcm.category_id = tpc.id AND tpcm.product_id = tp.id AND tp.id = tpt.owner_id AND tpt.language = 'en-US' GROUP BY `tp`.`id` ORDER BY `tp`.`created_datetime` DESC LIMIT 5

backend/index.php/catalog/products/review/index

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #10 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'yii2shopd.tprt.review' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
The SQL being executed was: SELECT COUNT(*) FROM (SELECT `tpr`.*, `tprt`.`review`, `tpt`.`name` AS `product_name` FROM tbl_product_category_mapping tpcm, tbl_product tp, `tbl_product_review` tpr, tbl_product_review_translated tprt, tbl_product_translated `tpt` WHERE tpcm.data_category_id = '1' AND tpcm.product_id = tp.id AND tpt.owner_id = tp.id AND tpt.language = 'en-US' AND tp.id = tpr.product_id 
AND tpr.status != 0 AND tpr.id = tprt.owner_id AND tprt.language = 'en-US' GROUP BY `tp`.`id`, `tpr`.`id`) `c`

Looks like the error is with the field tpt.name

**Comment by ushainformatique** [comment]
Hello,

It seems like the sql mode you have is causing the issue. Could you please change sql_mode = "" or "NO_ENGINE_SUBSTITUTION" in my.ini and test?

**Comment by ppblaauw** [comment]
Removing 'ONLY_FULL_GROUP_BY' from the settings for sql_mode solved the issue

It is now sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

Thanks
