### ISSUE TITLE
security bug - sending password in plaintext via email

### ISSUE THREAD

**Issue by pabloneruda1** [ushainformatique/whatacart#17]
Hello,
sending password by email is nonsense. Anyone can read the email along the way.
The password reset process has already programmed in Yii2 advanced app via confirmation link - you can be inspired.

Thanks for listening.
Pablo Neruda

**Comment by ushainformatique** [comment]
Thanks for the feedback. It means anyone can read any other email coming to your account. We already know about that but we made a choice of that. You could please change the way if you want to be like yii advanced app.

**Comment by pabloneruda1** [comment]
A strange choice, but OK
