### ISSUE TITLE
mysql 5.7 x64

### ISSUE THREAD

**Issue by akiraz2** [ushainformatique/whatacart#2]
On mysql 5.7 x64 I cant install whatacart

Next yii\db\Exception: SQLSTATE[HY000]: General error: 1364 Field 'password_reset_token' doesn't have a default value
The SQL being executed was: INSERT INTO `tbl_user` (`username`, `timezone`, `status`, `password_hash`, `type`, `person_id`, `auth_key`, `created_by`, `created_datetime`, `modified_by`, `modified_datetime`) VALUES ('admin', 'Europe/Moscow', 1, '$2y$13$1tAreMmhnwFyUUHz275skuumeYGkPwitKtd0qeuAVMfyMNfYWqmAm', 'system', 1, '5L2-_Tm8MAU3_jyIQ4zxTBAe2ow6B9yd', 1, '2017-01-13 15:53:13', 1, '2017-01-13 15:53:13') in Z:\whatacart\vendor\yiisoft\yii2\db\Schema.php:633

On mysql 5.6 x64 OK

**Comment by ushainformatique** [comment]
Closing the issue. It is being fixed as part of upcoming release 2.0.0.
