### ISSUE TITLE
An internal server error occurred.

### ISSUE THREAD

**Issue by moggiex** [ushainformatique/whatacart#21]
HI,

A fresh install and going to whatacart.local, the browser s redirected to this URL and simply the message "An internal server error occurred." is shown.

Then in the error logs, this is left behind, any ides on how to resolve this?

`[Wed Feb 14 22:03:27.467543 2018] [php7:notice] [pid 2068:tid 1968] [client 127.0.0.1:54629] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: A circular dependency is detected for bundle 'backend\\assets\\AppAsset'. in C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\View.php:295\nStack trace:\n#0 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\AssetBundle.php(125): yii\\web\\View->registerAssetBundle('backend\\\\assets\\\\...')\n#1 C:\\xampp\\htdocs\\whatacart\\whatacart\\protected\\backend\\views\\layouts\\main.php(12): yii\\web\\AssetBundle::register(Object(usni\\library\\web\\AdminView))\n#2 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\View.php(328): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\View.php(250): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\Controller.php(396): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(backend\\controllers\\home\\DefaultController))\n#5 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\Controller.php(382): yii\\base\\Controller->renderContent('<br/><br/>\\n<div...')\n#6 C:\\xampp\\htdocs\\whatacart\\whatacart\\protected\\backend\\controllers\\home\\DefaultController.php(54): yii\\base\\Controller->render('//error', Array)\n#7 [internal function]: backend\\controllers\\home\\DefaultController->actionError()\n#8 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)\n#9 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\Controller.php(156): yii\\base\\InlineAction->runWithParams(Array)\n#10 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\Module.php(523): yii\\base\\Controller->runAction('error', Array)\n#11 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(95): yii\\base\\Module->runAction('home/default/er...')\n#12 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(111): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidParamException))\n#13 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidParamException))\n#14 {main}\nPrevious exception:\nyii\\base\\InvalidParamException: The file or directory to be published does not exist: ..\\vendor\\bower/jquery/dist in C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\AssetManager.php:454\nStack trace:\n#0 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\AssetBundle.php(185): yii\\web\\AssetManager->publish('..\\\\vendor\\\\bower...', Array)\n#1 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\AssetManager.php(268): yii\\web\\AssetBundle->publish(Object(usni\\library\\web\\AssetManager))\n#2 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\AssetManager.php(243): yii\\web\\AssetManager->loadBundle('yii\\\\web\\\\JqueryA...', Array, true)\n#3 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\View.php(286): yii\\web\\AssetManager->getBundle('yii\\\\web\\\\JqueryA...')\n#4 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\View.php(291): yii\\web\\View->registerAssetBundle('yii\\\\web\\\\JqueryA...', NULL)\n#5 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\View.php(291): yii\\web\\View->registerAssetBundle('yii\\\\web\\\\YiiAsse...', NULL)\n#6 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\View.php(291): yii\\web\\View->registerAssetBundle('usni\\\\library\\\\we...', NULL)\n#7 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\AssetBundle.php(125): yii\\web\\View->registerAssetBundle('backend\\\\assets\\\\...')\n#8 C:\\xampp\\htdocs\\whatacart\\whatacart\\protected\\backend\\views\\layouts\\main.php(12): yii\\web\\AssetBundle::register(Object(usni\\library\\web\\AdminView))\n#9 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\View.php(328): require('C:\\\\xampp\\\\htdocs...')\n#10 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\View.php(250): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#11 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\Controller.php(396): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(backend\\controllers\\install\\DefaultController))\n#12 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\Controller.php(382): yii\\base\\Controller->renderContent('<div class="pag...')\n#13 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\ushainformatique\\yiichimp\\library\\modules\\install\\controllers\\DefaultController.php(59): yii\\base\\Controller->render('//install/welco...')\n#14 C:\\xampp\\htdocs\\whatacart\\whatacart\\protected\\backend\\controllers\\install\\DefaultController.php(44): usni\\library\\modules\\install\\controllers\\DefaultController->actionIndex()\n#15 [internal function]: backend\\controllers\\install\\DefaultController->actionIndex()\n#16 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)\n#17 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\Controller.php(156): yii\\base\\InlineAction->runWithParams(Array)\n#18 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\Module.php(523): yii\\base\\Controller->runAction('', Array)\n#19 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\web\\Application.php(102): yii\\base\\Module->runAction('install/default', Array)\n#20 C:\\xampp\\htdocs\\whatacart\\whatacart\\vendor\\yiisoft\\yii2\\base\\Application.php(380): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))\n#21 C:\\xampp\\htdocs\\whatacart\\whatacart\\backend\\index.php(47): yii\\base\\Application->run()\n#22 {main}\n$_SERVER = [\n    'REDIRECT_MIBDIRS' => 'C:/xampp/php/extras/mibs',\n    'REDIRECT_MYSQL_HOME' => '\\\\xampp\\\\mysql\\\\bin',\n    'REDIRECT_OPENSSL_CONF' => 'C:/xampp/apache/bin/openssl.cnf',\n    'REDIRECT_PHP_PEAR_SYSCONF_DIR' => '\\\\xampp\\\\php',\n    'REDIRECT_PHPRC' => '\\\\xampp\\\\php',\n    'REDIRECT_TMP' => '\\\\xampp\\\\tmp',\n    'REDIRECT_STATUS' => '200',\n    'MIBDIRS' => 'C:/xampp/php/extras/mibs',\n    'MYSQL_HOME' => '\\\\xampp\\\\mysql\\\\bin',\n    'OPENSSL_CONF' => 'C:/xampp/apache/bin/openssl.cnf',\n    'PHP_PEAR_SYSCONF_DIR' => '\\\\xampp\\\\php',\n    'PHPRC' => '\\\\xampp\\\\php',\n    'TMP' => '\\\\xampp\\\\tmp',\n    'HTTP_HOST' => 'whatacart.local',\n    'HTTP_CONNECTION' => 'keep-alive',\n    'HTTP_PRAGMA' => 'no-cache',\n    'HTTP_CACHE_CONTROL' => 'no-cache',\n    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36',\n    'HTTP_ACCEPT' => 'image/webp,image/apng,image/*,*/*;q=0.8',\n    'HTTP_REFERER' => 'http://whatacart.local/backend/install/default',\n    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',\n    'HTTP_ACCEPT_LANGUAGE' => 'en-GB,en-US;q=0.9,en;q=0.8',\n    'HTTP_COOKIE' => 'LCSESSID=0aug11490c1m2hi3s1cldnvota; language_code=en; cart[uid]=5a84ab477e352; currency_code=GBP; PHPBACKSESSID=qoqse4e91b9o9fltmjs78m23vq',\n    'PATH' => 'C:\\\\Program Files (x86)\\\\Intel\\\\iCLS Client\\\\;C:\\\\Program Files\\\\Intel\\\\iCLS Client\\\\;C:\\\\Windows\\\\system32;C:\\\\Windows;C:\\\\Windows\\\\System32\\\\Wbem;C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\;C:\\\\Program Files (x86)\\\\Intel\\\\Intel(R) Management Engine Components\\\\DAL;C:\\\\Program Files\\\\Intel\\\\Intel(R) Management Engine Components\\\\DAL;C:\\\\Program Files (x86)\\\\Intel\\\\Intel(R) Management Engine Components\\\\IPT;C:\\\\Program Files\\\\Intel\\\\Intel(R) Management Engine Components\\\\IPT;C:\\\\Program Files (x86)\\\\NVIDIA Corporation\\\\PhysX\\\\Common;C:\\\\Program Files (x86)\\\\Skype\\\\Phone\\\\;C:\\\\xampp\\\\php;C:\\\\ProgramData\\\\
`

**Comment by ushainformatique** [comment]
I am sorry for the delayed reply. Not well for quite long time. I am not sure how you have htdocs\whatacart\whatacart? Can you please install just at the whatacart level?

**Comment by moggiex** [comment]
Closing as moved on from the project
