### ISSUE TITLE
Can not install 

### ISSUE THREAD

**Issue by nimeshjainjbsols** [ushainformatique/whatacart#22]
Hi, I'm trying to install whatacart on local machine, but getting below error:
SQLSTATE[HY000]: General error: 1364 Field 'path' doesn't have a default value The SQL being executed was: INSERT INTO `tbl_group` (`name`, `parent_id`, `level`, `status`, `category`, `created_by`, `modified_by`, `created_datetime`, `modified_datetime`) VALUES ('Administrators', 0, 0, 1, 'system', 1, 1, '2018-05-21 09:29:38', '2018-05-21 09:29:38')

**Comment by ushainformatique** [comment]
In case you are getting the following errors

No default value is provided for a column
Error while adding the indexes
Please add the following line to either my.ini or my.cnf based on your configuration.

sql-mode = ""

OR

sql-mode = "NO_ENGINE_SUBSTITUTION"

**Comment by ushainformatique** [comment]
In that case, just go to database table, and set the default value for path or you can change the code if you want by setting the path.

**Comment by ushainformatique** [comment]
Any updates on it?

**Comment by shoniisra** [comment]
I was trying to modify the sql code but it doesnt work.
The right solucion is edit the my.ini file 
(if you're using wamp its on C:/wamp64/bin/mysql/mysql*.*.**/my.ini )

**Comment by ushainformatique** [comment]
Closing it.
