### ISSUE TITLE
Not able to install 

### ISSUE THREAD

**Issue by neeraj24a** [ushainformatique/whatacart#23]
Getting below error messages while installing

Attached the screenshot below.

Fatal error: Uncaught exception 'yii\web\HeadersAlreadySentException' with message 'Headers already sent in C:\xampp\htdocs\whatacart\vendor\ushainformatique\yiichimp\library\modules\install\controllers\DefaultController.php on line 109.' in C:\xampp\htdocs\whatacart\vendor\yiisoft\yii2\web\Response.php:366 Stack trace: #0 C:\xampp\htdocs\whatacart\vendor\yiisoft\yii2\web\Response.php(339): yii\web\Response->sendHeaders() #1 C:\xampp\htdocs\whatacart\vendor\yiisoft\yii2\web\ErrorHandler.php(135): yii\web\Response->send() #2 C:\xampp\htdocs\whatacart\vendor\yiisoft\yii2\base\ErrorHandler.php(262): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException)) #3 [internal function]: yii\base\ErrorHandler->handleFatalError() #4 {main} thrown in C:\xampp\htdocs\whatacart\vendor\yiisoft\yii2\web\Response.php on line 366

![capture](https://user-images.githubusercontent.com/2338927/41341038-588dc1fc-6f16-11e8-82c6-140256e6367e.PNG)

**Comment by ushainformatique** [comment]
Hello,

Are you able to reinstall it successfully?

**Comment by neeraj24a** [comment]
Still getting same error when i retried installing the application.

**Comment by ushainformatique** [comment]
Its weird because we have checked on many systems and it is working fine. Which PHP version you are using and which os?

**Comment by MageloPST** [comment]
Hello there.
Im having same problem plus another one related to Swiftmailer i think :cry: 
If you could give some directions about those errors it would be great.

![imagen](https://user-images.githubusercontent.com/22962123/41824968-ae4ebf8a-77de-11e8-994b-3d2ab143ea87.png)

Im using php 7.2 by the way

**Comment by ushainformatique** [comment]
Hello,

Let me test it on php 7.2 and get back to you.

**Comment by ushainformatique** [comment]
I have installed it on 7.0.2 and it is working fine. Can we do a teamviewer session so that i can see the issue?

**Comment by MageloPST** [comment]
Awesome... Installing sendmail did the trick... Can I ask you why? I mean.. What is sendmail used for?
Thanks.

By the way... The other error stills happening... But installation was successfull

![image](https://user-images.githubusercontent.com/22962123/42072376-c8b50452-7b25-11e8-9f6f-71505d47e88d.png)

**Comment by ushainformatique** [comment]
Closing the issue. Swiftmailer issue fixed in release 2.0.2
