### ISSUE TITLE
Old issue

### ISSUE THREAD

**Issue by frankin94** [ushainformatique/whatacart#25]
Warning: require(./vendor/ushainformatique/yiichimp/library/config/bootstrap.php): failed to open stream: No such file or directory in /var/www/vps16705/data/www/pubg.likearmy.pw/index.php on line 28

Fatal error: require(): Failed opening required './vendor/ushainformatique/yiichimp/library/config/bootstrap.php' (include_path='.:/opt/php56/share/pear:/opt/php56/share/php/php') in /var/www/vps16705/data/www/pubg.likearmy.pw/index.php on line 28

**Comment by ushainformatique** [comment]
Hello,

Is vendor folder there?

**Comment by ushainformatique** [comment]
Closing it.
