### ISSUE TITLE
Fatal error: Cannot use 'Object' as class name as it is reserved in

### ISSUE THREAD

**Issue by FabioFabbri** [ushainformatique/whatacart#26]
PHP version 7.2.5 cannot open the installer project. 
Error generated on line 77 of \whatacart\vendor\yiisoft\yii2\base\Object.php 
From PHP 7.2.x Object is a reserved name and on yii was changed after 2.0.12.
There is a way to fix this in whatacart package or i have to rollback to the PHP version 7.0.X?
Thanks!

**Comment by ushainformatique** [comment]
I would say please return back to 7.0.X as here the issue is related to Yii version.

**Comment by dpchami** [comment]
I have facing the same challenge  _Cannot use 'Object' as class name as it is reserved_,  am using PHP 7.2.7. There is no way to save this rather than returning to previous version?

**Comment by ushainformatique** [comment]
Yup please revert back to earlier version of PHP. On 7.2.7 it would not work.

**Comment by ushainformatique** [comment]
Closing this issue.

**Comment by ushainformatique** [comment]
We would be soon releasing it for PHP 7.2.x
