### ISSUE TITLE
[SECURITY] Shipping cost not calculated correctly

### ISSUE THREAD

**Issue by francispage** [ushainformatique/whatacart#27]
The shipping cost on the order review page is not calculated. It is taken from the checkout form. ($checkout->deliveryOptionsEditForm->shipping_fee)

If you add new items to the cart and you refresh the page the shipping is not updated.

Everything should be recalculated when the page is refreshed.

**How to reproduce:**

- Configure fixed rate shipping of 15$ with perItem type
- add one product to the cart
- checkout until you see the review order page (shipping is 15)
- open new tab and add 3 new items to the cart
- come back to first page and refresh the page (shipping is still 15$ instead of 60$)

The shipping will still be the cost for only one item instead of 4 and it is that cost that is sent to paypal.

/Francis

**Comment by ushainformatique** [comment]
This is fixed. Please check on release 2.0.2
