### ISSUE TITLE
Error in BaseNotificationService.php line140 while installing in Windows

### ISSUE THREAD

**Issue by ciapistess** [ushainformatique/whatacart#31]
Hello and thanks for your effort in developing WhatACart. 
Here is my problem:

The installation process proceeds up to the creation of the tables  (progress at 50%),
then it stops with an 'internal error' message. 
Retrying with $debug = true, I see the guilty line 140 in file
 C:\xampp744\htdocs\vstore\vendor\ushainformatique\yiichimp\library\notifications\BaseNotificationService.php

The error is "Trying to access array offset on value of type bool".
This is what happens:
        $super  = UserDAO::getById(User::SUPER_USER_ID);
        if($email == null)
        {
          $email = $super['email'];   <<<<<< ERROR

AAMOF, table tbl_user and tbl_person are empty, so no surprise that UserDAO::getById() returns false.
Actually, all the tables are empty but tbl_configuration (19 records).

BTW, I tried with both demo data and without demo data, in case it matters.

This happens to me in Windows, both with XAMPP 7.4.3 and 7.4.4.
However, installation on Ubuntu completed with no problems, so it sounds to be related with configuration, I suppose.

Here is che complete stack. I could send you the whole debug page if needed (but I can't see any 'attachment' button here ...)
1. in C:\xampp744\htdocs\vstore\vendor\ushainformatique\yiichimp\library\notifications\BaseNotificationService.php at line 140
2. in C:\xampp744\htdocs\vstore\vendor\ushainformatique\yiichimp\library\notifications\BaseNotificationService.php at line 140 – yii\base\ErrorHandler::handleError(8, 'Trying to access array offset on...', 'C:\xampp744\htdocs\vstore\vendor...', 140, ...)
3. in C:\xampp744\htdocs\vstore\vendor\ushainformatique\yiichimp\library\notifications\BaseNotificationService.php at line 61 – usni\library\notifications\BaseNotificationService::getSystemFromAddressData()
4. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\base\BaseObject.php at line 109 – usni\library\notifications\BaseNotificationService::init()
5. yii\base\BaseObject::__construct([])
6. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\di\Container.php at line 375 – ReflectionClass::newInstanceArgs([[]])
7. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\di\Container.php at line 156 – yii\di\Container::build('usni\library\modules\users\servi...', [], [])
8. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\BaseYii.php at line 345 – yii\di\Container::get('usni\library\modules\users\servi...', [])
9. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\base\Component.php at line 750 – yii\BaseYii::createObject('usni\library\modules\users\servi...')
10. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\base\Component.php at line 734 – yii\base\Component::attachBehaviorInternal('notifyService', 'usni\library\modules\users\servi...')
11. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\base\Component.php at line 516 – yii\base\Component::ensureBehaviors()
12. in C:\xampp744\htdocs\vstore\vendor\ushainformatique\yiichimp\library\modules\users\business\Manager.php at line 55 – yii\base\Component::on('afterUpdate', [usni\library\modules\users\business\Manager, 'processAfterUpdate'])
13. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\base\BaseObject.php at line 109 – usni\library\modules\users\business\Manager::init()
14. in C:\xampp744\htdocs\vstore\vendor\ushainformatique\yiichimp\library\business\Manager.php at line 81 – yii\base\BaseObject::__construct(['userId' => 1])
15. in C:\xampp744\htdocs\vstore\vendor\ushainformatique\yiichimp\library\modules\install\business\InstallManager.php at line 165 – usni\library\business\Manager::getInstance(['userId' => 1])
16. in C:\xampp744\htdocs\vstore\vendor\ushainformatique\yiichimp\library\modules\install\controllers\DefaultController.php at line 140 – usni\library\modules\install\business\InstallManager::createSuperUser(usni\library\modules\install\dto\InstallFormDTO)
17. usni\library\modules\install\controllers\DefaultController::actionRunInstallation()
18. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\base\InlineAction.php at line 57 – call_user_func_array([backend\controllers\install\DefaultController, 'actionRunInstallation'], [])
19. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\base\Controller.php at line 157 – yii\base\InlineAction::runWithParams([])
20. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\base\Module.php at line 528 – yii\base\Controller::runAction('run-installation', [])
21. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\web\Application.php at line 103 – yii\base\Module::runAction('install/default/run-installation', [])
22. in C:\xampp744\htdocs\vstore\vendor\yiisoft\yii2\base\Application.php at line 386 – yii\web\Application::handleRequest(yii\web\Request)
23. in C:\xampp744\htdocs\vstore\backend\index.php at line 47 – yii\base\Application::run()

**Comment by ushainformatique** [comment]
Ok, it seems to be weird. I would check it and get back to you. Ideally tbl_user should be populated and after that mail is called for as far as i remember the logic without looking into code. Thanks for letting me know. I would check and update on it.

**Comment by goodwind10** [comment]
Same issue is happening on Mac with apache server and php 7.4 with the install from composer and downloading the 2.0.6 version file.

**Comment by ushainformatique** [comment]
Hello,

I think its because of php version. If you use less than php 7.3 it should
work fine. In the line you have pasted look for value used in getById
function,  the problem is of type. If you strongly typed it as int, it
would work fine.

Regards,
Mayank

**Comment by goodwind10** [comment]
Mayark, thank you for the quick response.

It seems that just by downgrading the php version to 7.3 fixed the issue. None the less I verified the issue and found out it is related to the way that PHP 7.4 treats MySQL::query() when no results are found.

In PHP 7.3 the empty query returns an empty first row as an assoc array, while in PHP 7.4 If no results are found then it returns FALSE and if there is a result then it returns the first row as an assoc array. 

So to fix this issue you need to properly validate query responses. In our case you need to modify the `ushainformatique/yiichimp/library/notifications/BaseNotificationService.php` file and the `protected/common/modules/catalog/modules/productCategories/models/ProductCategory.php` file

So change this:
`$super  = UserDAO::getById(User::SUPER_USER_ID);
        if($email == null)
        {
            $email = $super['email'];
        }
        if($name == null)
        {
            $name = $super['firstname'] . ' ' . $super['lastname'];
        }
        return [$name, $email];`
to this:
`$super  = UserDAO::getById(User::SUPER_USER_ID);
        if($super != 0) {
            if($email == null)
            {
                $email = $super['email'];
            }
            if($name == null)
            {
                $name = $super['firstname'] . ' ' . $super['lastname'];
            }
        }
        return [$name, $email];`

in the first file; and this:
`$this->savedDataCategoryId  = $category['data_category_id'];`
to this:
`$this->savedDataCategoryId  = isset($category['data_category_id']) ? $category['data_category_id'] : null;`
in the second file

**Comment by ushainformatique** [comment]
New release supporting PHP 8 is there.
