### ISSUE TITLE
PHP8.1 or above

### ISSUE THREAD

**Issue by neoacevedo** [ushainformatique/whatacart#35]
I saw some activity in the project but I'm asking if actually is alive. Meanwhile: when will be a support for PHP 8.1 or above?

**Comment by msinghai** [comment]
Yes it is alive. We would shortly update it to support PHP 8.1 and above.

**Comment by ushainformatique** [comment]
The release supporting php 8 is live.

**Comment by ushainformatique** [comment]
Closing this as release supporting php 8 is live.
