### ISSUE TITLE
Internationalization multilanguage I18N 

### ISSUE THREAD

**Issue by nandes2062** [ushainformatique/whatacart#4]
I do not know if there is a possibility that Whatacart is multilanguage

**Comment by msinghai** [comment]
Yes it does work. Please add a language from the backend for example french.

There are two scenarios

a) If you add the language to already installed app, than the old models are not translated and you need to save each of them manually. Auto translation of old models are not supported yet.
b) If you are installing fresh, please add french language to LanguageDataManager and run the install. You would have the application installed in multi language.

**Comment by ushainformatique** [comment]
Closing the issue.
