### ISSUE TITLE
Adding A Blog Module

### ISSUE THREAD

**Issue by eddingtonm** [ushainformatique/whatacart#6]
Hi, I would like to add a Blog Module, whee the admin can publish Product-related posts.
I would like to know how to add the "Blogging module support for Yii2" by @aaiyo 

I have tried to place it in the Module directory under the Frontend view but when I add the necessary config details into ModuleConfig.php , It gives me an 

> Error (#2)
An internal server error occurred.
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.

Where should I add the Module so that it serves as a seperate (More like sub-domain) feature of the overall web-app?

Thanks.

**Comment by ushainformatique** [comment]
Hello, you need to have an init.php file inside config folder in the module. You can refer to any existing modules in the system. Than simply run the url with the parameter clearCache=true and it should get loaded.

**Comment by eddingtonm** [comment]
Thank you very much. It worked.

**Comment by ushainformatique** [comment]
Closing the issue.
