### ISSUE TITLE
install error deploying on a domain

### ISSUE THREAD

**Issue by ish256** [ushainformatique/whatacart#8]
I am currently getting the following error when trying to install whatacart on a lamp stack droplet

`PHP Fatal error:  require(): Failed opening required '/var/www/html/laza-ny/protected/common/config/instance.install.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/laza-ny/index.php on line 18`

Any suggestions on how to proceed?

**Comment by ushainformatique** [comment]
First of all check is the file is there or not secondly check the permissions with which the file is getting created.

**Comment by ish256** [comment]
Thanks! I got it running.
