### ISSUE TITLE
Strict model MySQL

### ISSUE THREAD

**Issue by githubjeka** [ushainformatique/whatacart#9]
```
In case you are getting the following errors

No default value is provided for a column
Error while adding the indexes
Please add the following line to either my.ini or my.cnf based on your configuration.

sql-mode = ""

OR

sql-mode = "NO_ENGINE_SUBSTITUTION"
```

Please fix this.
STRICT mode on MySQL cannot always be turned off.

**Comment by ushainformatique** [comment]
Ok sure, we would fix this as a part of next release.

**Comment by rossaddison** [comment]
Post installation encouraging comment: ....File: Protected/Common/Config/Instance.php >  $debug = true  > $environment = 'dev' > generated...SQLSTATE[4200] error. Installation date: 29/10/2017... Version 2.0.1....Server running:.....  WAMP 3.0.6..... Apache 2.4.23..... PHP 7.0.10.....MySQL 5.7.14 
bin\mysql\mysql5.7.14\my.ini......  sql-mode = '"" .......  did the trick. Thanks  Githubjeka and 
https://bitbucket.org/ushainformatique/whatacart/issues/9/install-error.

**Comment by ushainformatique** [comment]
Its nice

**Comment by ciapistess** [comment]
@rossaddison thanks for the tip. 
However it does not work for me. 
I get the error during installation - should it apply even in that case?
Any suggestion to debug, check the effect of the 'attributes' parameter ?

**Comment by akshay48299** [comment]
@rossaddison 

Yes, Its working fine 

Above comment updated: 02/11/2017:
If you cannot set sql-mode = "" on the server then you can set it at runtime by adjusting the
following php file: protected/common/config/main-local.php.

Insert the following line of code after 'schemaCache' => 'cache',:

'attributes' => [PDO::MYSQL_ATTR_INIT_COMMAND => 'SET sql_mode=""'],

**Comment by ushainformatique** [comment]
Closing the issue
